import Link from "next/link";
import { prisma } from "@/src/lib/db";

export const dynamic = "force-dynamic";

export default async function StatusPage() {
  let sources: any[] = [];
  let runs: any[] = [];
  let counts = { articles: 0, stories: 0 };
  try { const [sourceRows, runRows, articleCount, storyCount] = await Promise.all([prisma.source.findMany({ include: { category: true }, orderBy: { name: "asc" } }), prisma.ingestionRun.findMany({ orderBy: { startedAt: "desc" }, take: 10 }), prisma.article.count(), prisma.story.count()]); sources = sourceRows; runs = runRows; counts = { articles: articleCount, stories: storyCount }; } catch {}
  return <div className="app-shell"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">NI</span><span><span className="brand-name">News Intelligence</span><span className="brand-sub">System status</span></span></Link><div className="top-actions"><Link className="outline-button" href="/">Dashboard</Link></div></header><main className="main"><div className="page-heading"><div><div className="eyebrow">Admin / status</div><h1>Pipeline health.</h1><p>See source health, ingestion activity, and the current size of the reporting graph.</p></div></div><div className="metric-row" style={{maxWidth: 520, marginBottom: 24}}><div className="metric"><strong>{sources.filter((source) => source.enabled).length}</strong><span>enabled sources</span></div><div className="metric"><strong>{counts.articles}</strong><span>articles</span></div><div className="metric"><strong>{counts.stories}</strong><span>stories</span></div></div><section className="detail-panel"><h2>Sources</h2><div className="source-list">{sources.map((source) => <div className="source-item" key={source.id}><span><span className={`status-dot ${source.lastError ? "error" : ""}`}></span><strong>{source.name}</strong><br /><small>{source.category.name} · {source.lastSuccessAt ? `last success ${new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(source.lastSuccessAt)}` : "not fetched yet"}</small></span><span>{source.failureCount ? `${source.failureCount} failure${source.failureCount === 1 ? "" : "s"}` : "healthy"}</span></div>)}</div></section><section className="detail-panel" style={{marginTop: 14}}><h2>Ingestion history</h2><div className="source-list">{runs.map((run) => <div className="source-item" key={run.id}><span><strong>{run.status}</strong><br /><small>{new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(run.startedAt)}</small></span><span>{run.articlesFetched} fetched · {run.storiesCreated} stories</span></div>)}</div></section></main></div>;
}
