import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/src/lib/db";

export const dynamic = "force-dynamic";

export default async function StoryPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const story = await prisma.story.findUnique({ where: { id }, include: { primaryCategory: true, articles: { include: { source: true }, orderBy: { publishedAt: "desc" } }, storySources: { include: { source: true, article: true } } } });
  if (!story) notFound();
  const facts = Array.isArray(story.keyFacts) ? story.keyFacts as string[] : [];
  return <div className="app-shell"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">NI</span><span><span className="brand-name">News Intelligence</span><span className="brand-sub">A calmer daily briefing</span></span></Link><div className="top-actions"><Link className="outline-button" href="/">← Dashboard</Link></div></header><main className="main"><article className="story-page"><Link className="back-link" href="/">← Back to your briefing</Link><div className="eyebrow" style={{marginTop: 30}}>{story.primaryCategory.name} · {story.confidence}</div><h1>{story.headline}</h1><p className="story-deck">{story.summary || "This story does not have an AI summary yet. Run summarization after collecting source material."}</p><div className="detail-grid"><section className="detail-panel full"><h2>Why it matters</h2><p>{story.whyItMatters || "No analysis has been generated yet. The app keeps this separate from sourced facts."}</p></section><section className="detail-panel"><h2>Key facts</h2>{facts.length ? <ul>{facts.map((fact) => <li key={fact}>{fact}</li>)}</ul> : <p>Key facts will appear after reliable source context is available.</p>}</section><section className="detail-panel"><h2>What happens next</h2><p>{story.whatHappensNext || "No clear next step is reported."}</p></section><section className="detail-panel full"><h2>Sources</h2><div className="source-list">{story.articles.map((article) => <div className="source-item" key={article.id}><span>{article.source.name} · {article.publishedAt ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(article.publishedAt) : "date unavailable"}</span><a href={article.url} target="_blank" rel="noreferrer">Open original ↗</a></div>)}</div></section><section className="detail-panel full"><h2>Timeline of updates</h2><div className="timeline">{story.articles.map((article) => <div className="timeline-item" key={article.id}><strong>{article.title}</strong><span>{article.publishedAt ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(article.publishedAt) : "Publication date unavailable"} · {article.source.name}</span></div>)}</div></section></div></article></main></div>;
}
